/*
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
    The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?
*/

class Problem_12{
    /* returns the nth triangle number; that is, the sum of all the natural numbers less than, or equal to, n */
    public static int triangleNumber(int n) {
        int sum = 0;
        for (int i = 0; i <= n; i++)
            sum += i;
        return sum;
    }
    public static void main(String[] args) {
        int j = 0; 
        int n = 0;
        int noOfDiv = 0; 
        while (noOfDiv<= 500) { //checks if no of divisors<=500
            noOfDiv= 0;
            j++;
            n = triangleNumber(j);
            // checking for divisors and counting them untill sqrt(n)
            for (int i = 1; i <= Math.sqrt(n); i++)
                if (n % i == 0)
                    noOfDiv++;
            // 1 to the square root of the number holds exactly half of the divisors
            // so multiply it by 2 to include the other corresponding half
            noOfDiv*= 2;
        }        
        System.out.println(n);
    }
}