#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a,b=1,2
sm=0
i=0
while True:
	if a%2==0:
		sm+=a
	elif a>=4000000:
		break
	if b%2==0:
		sm+=b
	elif b>=4000000:
		break
	a+=b
	b+=a
print('Sum is ',sm)
